# Generated by Django 5.0.7 on 2024-07-31 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('symbol', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['name', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=50)),
                ('iban', models.CharField(blank=True, max_length=25, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_currency', to='bank_account.currency')),
            ],
            options={
                'ordering': ['name', 'bank'],
            },
        ),
    ]
