# Generated by Django 5.0.7 on 2024-08-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
