# Generated by Django 5.0.7 on 2024-09-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currency_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
