# Generated by Django 5.0.7 on 2024-09-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_bankaccount_currency_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='currency_balance',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
