# Generated by Django 5.0.7 on 2024-08-27 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('invoice_closing_date', models.IntegerField(default=1, help_text='Informe o dia do fechamento da fatura (1 a 31).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('day_of_invoice', models.IntegerField(default=1, help_text='Informe o dia do vencimento da fatura (1 a 31).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_currency', to='bank_account.currency')),
                ('standart_debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standart_bank', to='bank_account.bankaccount')),
            ],
            options={
                'ordering': ['name', 'bank', 'invoice_closing_date'],
            },
        ),
    ]
