# Generated by Django 5.0.7 on 2024-08-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_account', '0001_initial'),
        ('categories', '0002_alter_category_name_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('description', models.CharField(max_length=120)),
                ('debit_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_posting_bank_account', to='bank_account.bankaccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_posting_category', to='categories.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_posting_category', to='categories.subcategory')),
            ],
        ),
    ]
