# Generated by Django 5.0.7 on 2024-08-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountposting',
            name='credit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='accountposting',
            name='debit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
