# Generated by Django 5.0.7 on 2024-08-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_postings', '0002_alter_accountposting_credit_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountposting',
            name='expiry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accountposting',
            name='issue_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accountposting',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
