# Generated by Django 5.0.7 on 2025-02-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_postings', '0005_alter_accountposting_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountposting',
            name='transfer_pair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_transfer', to='account_postings.accountposting'),
        ),
    ]
