# Generated by Django 5.0.7 on 2025-02-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_postings', '0006_accountposting_transfer_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountposting',
            name='transfering',
            field=models.BooleanField(default=False),
        ),
    ]
