# Generated by Django 5.0.7 on 2024-08-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('type', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('T', 'Transferência')], max_length=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
